### ISSUE TITLE
Error in parameter.h & bmploader.h

### ISSUE THREAD

**Issue by arowana16** [AdarshRevankar/GRAPHICAL-SIMULATION-OF-DESKTOP-AND-ITS-COMPONENTS#2]
ide-codeblocks
i have some error reagarding scalar braces pls check this
![Capture12r2wf](https://user-images.githubusercontent.com/64064631/79836173-6d174f80-83cd-11ea-8f75-d4c0ae82ef4d.PNG)

**Comment by AdarshRevankar** [comment]
Try to rename `fopen_s` to `fopen` I think this will resolve the error at Line 19

**Comment by AdarshRevankar** [comment]
![Annotation 2020-04-21 124825](https://user-images.githubusercontent.com/48080453/79836986-6b01c080-83ce-11ea-9893-21a37880f52e.jpg)
This might resolve the error at 142. Because this kind of declaration is not accepted by the Codeblock, I think.

change declaration from
`const char* texPath[ ] = { ... }`

to
`const char* texPath[40] = { ... }`

**Comment by AdarshRevankar** [comment]
This change will surely work. Remove the **inner brackets**.

`const char* texPath[ ] = {			"data/motherboard_back.bmp",
									"data/motherboard_front.bmp",
									"data/wooden_finsih.bmp",
									"data/motherboard_usb.bmp",
									"data/steel_texture.bmp",
									"data/razor_logo.bmp",
									"data/case_side_bar.bmp",
									"data/inside_wall.bmp",
									"data/motherboard_vga.bmp",
									"data/fan_logo.bmp",
									"data/rim_right.bmp",
									"data/rim_left.bmp",
									"data/rim_top.bmp",
									"data/rim_bottom.bmp",
									"data/case_behind.bmp",
									"data/hdd.bmp",
									"data/ramstick.bmp",
									"data/psu_front.bmp",
									"data/psu_top.bmp",
									"data/psu_left.bmp" ,
									"data/Chipset.bmp",
									"data/chipset_back.bmp",
									"data/gpu_front.bmp",
									"data/gpu_lower.bmp",
									"data/gpu_left.bmp",
									"data/gpu_back.bmp",
									"data/gpu_side.bmp",
									"data/wall.bmp",
									"data/table.bmp",
									"data/drawers.bmp",
									"data/ceiling.bmp",
									"data/couch_seat.bmp",
									"data/couch_pillow.bmp",
									"data/tv.bmp",
									"data/pic.bmp",
									"data/tv_table.bmp",
									"data/speaker.bmp",
									"data/keyboard.bmp",
									"data/acer_wallpaper.bmp",
									"data/acer_wallpaper_blankscreen.bmp"
};`

Please let me know if this is working

**Comment by arowana16** [comment]
yes...parmeter.h is solved...
but bmploader is not solved after renaming it also..
find attachment
![1234sdv](https://user-images.githubusercontent.com/64064631/79840041-fbda9b00-83d2-11ea-9c2e-11d73b87de70.PNG)

**Comment by AdarshRevankar** [comment]
In _line 19_,
1. Keep `fopen_s` as the function for reading bitmap from file.
2. Include the `#include<stdio.h>` library so as to provide `fopen_s`

Let me know if this works 😊

**Comment by arowana16** [comment]
after adding #include<stdio.h> it says... fopen_s is not declared in this scope

**Comment by AdarshRevankar** [comment]
> after adding #include<stdio.h> it says... fopen_s is not declared in this scope

Try this

Replace the code 
`fopen_s(&file, filename, ​"​rb​"​);`

With
`
&file = fopen(filename,"rb");
`

This problem is caused because, `fopen_s ` is microsoft implemented deprecated method and hence it won't run without Windows SDK. So I think the above suggested implementation will work

Reference:
1. For the alternative implementation
https://stackoverflow.com/questions/1513209/is-there-a-way-to-use-fopen-s-with-gcc-or-at-least-create-a-define-about-it


2. For read binary cross verification https://stackoverflow.com/questions/2174889/whats-the-differences-between-r-and-rb-in-fopen

---
Let me knw if it solved this problem

**Comment by arowana16** [comment]
nope,i tried but its not solving..
used == for lvalue assignment no use..
![wffd](https://user-images.githubusercontent.com/64064631/79850433-8a561900-83e1-11ea-82ab-3e08d66fac5d.PNG)

**Comment by AdarshRevankar** [comment]
Check this code, I have installed Codeblocks and ran this code
This code works perfectly for me 

![Annotation 2020-04-21 164506](https://user-images.githubusercontent.com/48080453/79859986-85986180-83ef-11ea-9268-798c84b28320.jpg)

`file = fopen(filename, "rb");`

**Comment by AdarshRevankar** [comment]
Yes, bro... it's working fine now

I'll create a new branch for the **Codeblock** users since few syntaxes are different than **Visual Studio**. 
![Screenshot (193)](https://user-images.githubusercontent.com/48080453/79860377-3272de80-83f0-11ea-8f77-b486c77e2f29.png)

---

# Things to be Noted : Codeblocks Users
1. Change the file reading operation as: 
`file = fopen(filename, "rb")`
![Annotation 2020-04-21 164506](https://user-images.githubusercontent.com/48080453/79861314-db6e0900-83f1-11ea-98bb-66b98a85e789.jpg)

2. Change the `corecrt_math_defines.h` to `math.h` in the `parameter.h` file

3. Remove the inner **curly brazes** in the `parameter.h`.

4. Makes sure you have installed 32bit of Codeblocks

5. Add the `-m32` option in the build, since you have to target for 32bit version
![Annotation 2020-04-21 165511](https://user-images.githubusercontent.com/48080453/79861206-a3ff5c80-83f1-11ea-8ad0-9000f799c8f3.jpg)

6. Make sure linker has `freeglut` registered in it
![Annotation 2020-04-21 165429](https://user-images.githubusercontent.com/48080453/79861217-a95ca700-83f1-11ea-80f3-895d4b2a3e9b.jpg)

---

### Give the repository star ⭐ if you like it

**Comment by AdarshRevankar** [comment]
Check in your project whether there is folder `Data` ?
![twert](https://user-images.githubusercontent.com/48080453/79872201-1af12100-8403-11ea-9a84-7cd661a85a80.PNG)

Place the `Data` folder which contains bmp files in the project

or

### Clone the `master` I have updated all the code compatible for **Codeblocks**

**Comment by arowana16** [comment]
errors are solved..thanks for that..but
small problem while running....tht is path issue....plsz do tell how to solve tat..
i have added image files recursively to codeblocks,,
![fbfvcvvf](https://user-images.githubusercontent.com/64064631/79872376-58ee4500-8403-11ea-835a-d77d2f7ced4b.PNG)

**Comment by AdarshRevankar** [comment]
Open in file explorer, and you must have the **data** folder inside the project folder like this
![Annotation 2020-04-21 190856](https://user-images.githubusercontent.com/48080453/79872565-9226b500-8403-11ea-8170-d5ef5e40faab.jpg)

If it works fine, or else clone the `master`

**Comment by arowana16** [comment]
its there in project main folder...

**Comment by AdarshRevankar** [comment]
Try to clone the `master` and try to include `Freeglut` files I think everything will work fine. Because I have tried now.

**Comment by arowana16** [comment]
yes...but issues are wid path.. i guess..

sorry for Annoying You

thanks

**Comment by AdarshRevankar** [comment]
Its totally fine bro. is it the same error you are getting?

**Comment by arowana16** [comment]
No everything solved bro.....thanks...cheers:)
again i thank you bro....

**Comment by arowana16** [comment]
Nope...
Everything  Works Fine....Thanks Man...for your Patience and Helping me...

**Comment by AdarshRevankar** [comment]
Good Good... It's okay, If you want to do some contributions or improvements feel free.
Star the repository if you like ⭐. 

All the best with your project
